# Generated by Django 4.0.6 on 2022-08-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default="Hi i'm here.", max_length=40),
        ),
    ]
